version: "3.8"

services:
  spring-boot-app:
    image: nidhal198/tpfoyer:0.0.1 # Remplacez par votre image Docker
    ports:
      - "8085:8085"
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nidhal
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-nidhal:
    depends_on:
      - mysqlDb
    image: nidhal198/tpfoyer:0.0.1  # Utilisez ici la version spécifique 0.0.1
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqlDb:3306/nidhal?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "rootpassword",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
