# Use OpenJDK 17 as the base image
FROM openjdk:17

# Expose the port the app will run on
EXPOSE 8082

# Copy the built jar from the target directory into the container
ADD target/tpFoyer-17-0.0.2.jar /tpfoyer-0.0.2.jar

# Set the entrypoint to run the application
ENTRYPOINT ["java", "-jar", "/tpfoyer-0.0.2.jar"]
