version: "3.8"

services:
  mysqldb:
    image: mysql:8.3.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    ports:
      - 3306:3306
    volumes:
