version: "3.8"

services:
  mysqldb:
    image: mysql:8.3.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=rootpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql




  app-tp-foyer:
    depends_on:
      - mysqldb
    image: nidhal198/tpfoyer:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/tpfoyer_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    stdin_open: true
    tty: true

volumes:
  db:
